### ISSUE TITLE
Jwt parsing throws PrematureJwtException

### ISSUE THREAD

**Issue by nervehammer** [BrimeNotes/core#7]
Due to the use of nbf (not before) attribute in JWT, it throws this Exception please either remove this attribute or provide some small leeway, usually no more than a few minutes, to account for clock skew.
Use of this claim is OPTIONAL is you can easily remove it :)

**Comment by imujjwal96** [comment]
@nervehammer Please also send the log reports.

**Comment by nervehammer** [comment]
thanks for the quick fix :)

**Comment by nervehammer** [comment]
closing this old issue
